version: '3.1'
services:
  db:
    image: postgres
    container_name: cashmachine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sg
      POSTGRES_DB: cashmachine
    ports:
      - "5432:5432"
    volumes:
      - cashmachine:/var/lib/postgres

volumes:
  cashmachine: